# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.gr.dart
    - lib/**.riverpod.dart
    - lib/**.mocks.dart
    - test/**.mocks.dart
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    unused_local_variable: warning

linter:
  rules:
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    avoid_returning_this: true
    avoid_types_on_closure_parameters: true
    cascade_invocations: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_expression_function_bodies: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_named_constants: true
    use_super_parameters: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
